# Generated by Django 2.1.2 on 2018-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.CharField(max_length=50)),
                ('backend', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=50)),
                ('programmer', models.CharField(max_length=50)),
            ],
        ),
    ]
